services:
  rosbridge:
    build:
      context: .
      dockerfile: Dockerfile.rosbridge
    container_name: rosbridge
    environment:
      - ROS_DISTRO=jazzy
      - CYCLONEDDS_URI=file:///cyclonedds.xml
    volumes:
      - ./launch_rosbridge.launch.py:/ros2_ws/launch/launch_rosbridge.launch.py:ro
    ports:
      - "9090:9090"
    command: ["ros2", "launch", "/ros2_ws/launch/launch_rosbridge.launch.py"]
